# ==============================================================================
# الوظيفة الأساسية للملف: محرك تحليل السيرة الذاتية بالذكاء الاصطناعي (ATS Parser).
# الروابط أو الميزات: يقرأ ملفات PDF ويستخرج البيانات المهنية ويترجم اسم الجامعة.
# المتطلبات الخاصة: يعتمد على pdfplumber و deep-translator (GoogleTranslator).
# ==============================================================================

import os
import re
import logging
from typing import Dict, Optional

import pdfplumber
from deep_translator import GoogleTranslator

# ---------------------------------------------------------------------------
# Logging configuration (English only — per AI_AGENT_RULES.md §4 & §13)
# ---------------------------------------------------------------------------
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Regex patterns for BOTH Arabic and English CV formats produced by
# generate_dummy_cvs.py.  Each tuple is (arabic_pattern, english_pattern).
# ---------------------------------------------------------------------------
_PATTERNS = {
    "university": (
        r"الجامعة\s*:\s*([^\n]+)",
        r"University\s*:\s*([^\n]+)",
    ),
    "qualification": (
        r"المؤهل\s*:\s*([^\n]+)",
        r"Qualification\s*:\s*([^\n]+)",
    ),
    "experience": (
        r"خبرة\s*:\s*(\d+)",
        r"Experience\s*:\s*(\d+)",
    ),
    "skills": (
        r"المهارات\s*:\s*([^\n]+)",
        r"Skills\s*:\s*([^\n]+)",
    ),
}


def _extract_text_from_pdf(pdf_path: str) -> str:
    """Extract raw text from all pages of a PDF using pdfplumber.

    Args:
        pdf_path: Absolute or relative path to the PDF file.

    Returns:
        Concatenated text of all pages, joined by newlines.

    Raises:
        FileNotFoundError: If the PDF file does not exist at pdf_path.
    """
    if not os.path.exists(pdf_path):
        raise FileNotFoundError(f"CV file not found at path: {pdf_path}")

    with pdfplumber.open(pdf_path) as pdf:
        pages_text = [page.extract_text() or "" for page in pdf.pages]

    return "\n".join(pages_text)


def _extract_field(patterns: tuple, text: str) -> Optional[str]:
    """Try each regex pattern in turn and return the first captured group found.

    Args:
        patterns: A tuple of regex pattern strings to attempt in order.
        text:     The raw text to search within.

    Returns:
        The stripped captured group string, or None if no pattern matched.
    """
    for pattern in patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            return match.group(1).strip()
    return None


def _translate_to_english(text: str) -> str:
    """Translate text to English using GoogleTranslator (deep-translator).

    Detects the source language automatically.  If the text is already in
    English or translation fails, the original text is returned unchanged.

    Args:
        text: The text to translate (typically an Arabic university name).

    Returns:
        The English translation, or the original text on any failure.
    """
    try:
        translated = GoogleTranslator(source="auto", target="en").translate(text)
        if translated:
            return translated.strip()
        return text
    except Exception as exc:
        logger.warning("Translation failed for '%s': %s", text, exc)
        return text


def _is_arabic(text: str) -> bool:
    """Return True if the text contains at least one Arabic character.

    Args:
        text: Any string to check.

    Returns:
        True if one or more Arabic Unicode characters are present.
    """
    return bool(re.search(r"[\u0600-\u06FF]", text))


def parse_cv(pdf_path: str) -> Dict[str, Optional[str]]:
    """Parse a CV PDF and return a structured dictionary of professional data.

    Supports both Arabic-language and English-language CVs as generated by
    ``generate_dummy_cvs.py``.  Extracted fields:

    - ``university_ar``             – Raw university name as found in the PDF.
    - ``university_en``             – University name translated to English (used
                                       for QS Ranking dataset matching).
    - ``educational_qualification`` – Degree / qualification level.
    - ``years_of_experience``       – Integer-string representing years of experience.
    - ``skills``                    – Comma-separated list of skills.
    - ``raw_text``                  – Full extracted PDF text (useful for debugging).

    Args:
        pdf_path: The **full** filesystem path to the saved PDF file.

    Returns:
        A dictionary with the keys listed above.  Any field that could not be
        extracted will have a value of ``None``.
    """
    logger.info("ATS Parser: starting extraction for '%s'", pdf_path)

    raw_text = _extract_text_from_pdf(pdf_path)

    # --- Field extraction (tries Arabic pattern first, then English) ----------
    university_raw = _extract_field(_PATTERNS["university"], raw_text)
    qualification   = _extract_field(_PATTERNS["qualification"], raw_text)
    experience      = _extract_field(_PATTERNS["experience"], raw_text)
    skills          = _extract_field(_PATTERNS["skills"], raw_text)

    # --- University translation -----------------------------------------------
    if university_raw and _is_arabic(university_raw):
        university_en = _translate_to_english(university_raw)
        logger.info(
            "ATS Parser: translated university '%s' -> '%s'",
            university_raw,
            university_en,
        )
    elif university_raw:
        # Already in English — no translation needed
        university_en = university_raw
    else:
        university_en = None

    result = {
        "university_ar": university_raw,
        "university_en": university_en,
        "educational_qualification": qualification,
        "years_of_experience": experience,
        "skills": skills,
        "raw_text": raw_text,
    }

    logger.info(
        "ATS Parser: extraction complete — university_en=%s, qualification=%s, "
        "experience=%s years, skills=%s",
        university_en,
        qualification,
        experience,
        skills,
    )
    return result


# ---------------------------------------------------------------------------
# Quick CLI demo — run: python -m ai_engine.ats_parser
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    # Default to the standard dummy-CV directory
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cv_dir = os.path.join(BASE_DIR, "mysite", "static", "uploads", "customers", "cv")

    if not os.path.isdir(cv_dir):
        print(f"CV directory not found: {cv_dir}")
        sys.exit(1)

    for fname in sorted(os.listdir(cv_dir)):
        if fname.lower().endswith(".pdf"):
            full_path = os.path.join(cv_dir, fname)
            print(f"\n=== Parsing: {fname} ===")
            try:
                data = parse_cv(full_path)
                for key, value in data.items():
                    if key != "raw_text":
                        print(f"  {key}: {value}")
            except Exception as err:
                print(f"  ERROR: {err}")
