import { env } from "./env"

/**
 * API_CONFIG — Central API configuration for Faeda Jobs.
 * Endpoints map directly to the Flask backend blueprints and services.
 * Do NOT scatter fetch/axios calls in UI components — use service modules instead.
 */
export const API_CONFIG = {
  BASE_URL: env.VITE_API_URL,
  TIMEOUT: 10000,
  HEADERS: {
    Accept: "application/json",
  },
  ENDPOINTS: {
    AUTH: {
      LOGIN: "/login",
      REGISTER: "/register",
      LOGOUT: "/logout",
      FORGOT_PASSWORD: "/forgot_password",
      RESET_PASSWORD: "/reset_password",
      REDIRECTS: "/redirects",
      MY_PROFILE: "/my_profile",
      ME: "/api/v1/auth/me",
    },
    JOBS: {
      LIST: "/api/v1/jobs",
      DETAIL: (id: string) => `/api/v1/jobs/${id}`,
      APPLY: (id: string) => `/applyjob/${id}`,
      SAVE: (id: string) => `/api/v1/jobs/${id}/save`,
      SEARCH: "/api/v1/jobs",
      SUGGESTIONS: "/api/v1/jobs/suggestions",
    },
    COMPANIES: {
      LIST: "/api/v1/companies",
      DETAIL: (id: string) => `/api/v1/companies/${id}`,
      SUGGESTIONS: "/api/v1/companies/suggestions",
    },
    TEAMS: {
      LIST: "/api/v1/teams",
      DETAIL: (id: string) => `/api/v1/teams/${id}`,
      SUGGESTIONS: "/api/v1/teams/suggestions",
      CREATE: "/create_team",
    },
    PORTFOLIO: {
      DETAIL: (username: string) => `/api/v1/portfolio/${username}`,
    },
    POSTS: {
      LIST: "/api/v1/posts",
      DETAIL: (id: string | number) => `/api/v1/posts/${id}`,
      CREATE: "/api/v1/posts",
      LIKE: (id: string | number) => `/api/v1/posts/${id}/like`,
      COMMENTS: (id: string | number) => `/api/v1/posts/${id}/comments`,
      COMMENT_EDIT: (id: string | number) => `/api/v1/posts/comments/${id}`,
      COMMENT_DELETE: (id: string | number) => `/api/v1/posts/comments/${id}`,
      SHARE: (id: string | number) => `/api/v1/posts/${id}/share`,
      SAVE: (id: string | number) => `/api/v1/posts/${id}/save`,
      SAVED: "/api/v1/posts/saved",
      ANALYTICS: (id: string | number) => `/api/v1/campaigns/${id}/analytics`,
      BY_USER: "/api/v1/posts/by-user",
    },
    NOTIFICATIONS: {
      LIST: "/api/v1/notifications",
      READ: (id: string | number) => `/api/v1/notifications/${id}/read`,
      READ_ALL: "/api/v1/notifications/read-all",
    },
    CANDIDATES: {
      DASHBOARD: "/api/v1/candidate/dashboard",
      PROFILE: "/api/v1/candidate/profile",
      IDENTITY: "/api/v1/candidate/profile/identity",
      ABOUT: "/api/v1/candidate/profile/about",
      SKILLS: "/api/v1/candidate/profile/skills",
      EXPERIENCE: "/api/v1/candidate/profile/experience",
      EDUCATION: "/api/v1/candidate/profile/education",
      PROJECTS: "/api/v1/candidate/profile/projects",
      PROJECT_DELETE: (id: number) => `/api/v1/candidate/profile/projects/${id}`,
      CERTIFICATIONS: "/api/v1/candidate/profile/certifications",
      CERTIFICATION_DELETE: (id: number) => `/api/v1/candidate/profile/certifications/${id}`,
      PREFERENCES: "/api/v1/candidate/profile/preferences",
      VISIBILITY: "/api/v1/candidate/profile/visibility",
      CV_UPLOAD: "/api/v1/candidate/cv/upload",
      CV_DOWNLOAD: "/api/v1/candidate/cv/download",
      JOBS: "/api/v1/candidate/jobs",
      JOB_DETAIL: (id: string | number) => `/api/v1/candidate/jobs/${id}`,
      JOB_APPLY: (id: string | number) => `/api/v1/candidate/jobs/${id}/apply`,
      JOB_SAVE: (id: string | number) => `/api/v1/candidate/jobs/${id}/save`,
      APPLICATIONS_LIST: "/api/v1/candidate/applications",
      APPLICATION_DETAIL: (id: string | number) => `/api/v1/candidate/applications/${id}`,
      SAVED_JOBS: "/api/v1/candidate/saved-jobs",
      RECOMMENDED_JOBS: "/api/v1/candidate/jobs/recommended",
      TEAMS: "/api/v1/candidate/teams",
      TEAM_DETAIL: (id: string | number) => `/api/v1/candidate/teams/${id}`,
      TEAM_UPDATE: (id: string | number) => `/api/v1/candidate/teams/${id}`,
      TEAM_DELETE: (id: string | number) => `/api/v1/candidate/teams/${id}`,
      TEAM_LEAVE: (id: string | number) => `/api/v1/candidate/teams/${id}/leave`,
      TEAM_MEMBER_REMOVE: (teamId: string | number, memberUserId: string) => `/api/v1/candidate/teams/${teamId}/members/${memberUserId}`,
      TEAM_CANDIDATES_SEARCH: "/api/v1/candidate/teams/candidates/search",
      TEAM_INVITE: (teamId: string | number) => `/api/v1/candidate/teams/${teamId}/invite`,
      TEAM_INVITATIONS: "/api/v1/candidate/teams/invitations",
      TEAM_INVITATION_RESPOND: (invId: string | number) => `/api/v1/candidate/teams/invitations/${invId}/respond`,
      TEAM_INVITATION_CANCEL: (invId: string | number) => `/api/v1/candidate/teams/invitations/${invId}`,
      LEGACY_PROFILE: "/my_profile",
      EDIT_PERSONAL: "/edit-profile/personal_data",
      EDIT_JOB: "/edit-profile/job_data",
      EDIT_EDU: "/edit-profile/educational_data",
      APPLICATIONS: "/my-jobapplications",
      RECOMMENDATIONS: "/recommendations",
      SETTINGS: "/api/v1/candidate/settings",
      CHANGE_PASSWORD: "/api/v1/candidate/change-password",
    },
    COMPANY: {
      ME: "/api/v1/company/me",
      PROFILE: "/api/v1/company/profile",
      LOGO_UPLOAD: "/api/v1/company/logo",
      DASHBOARD: "/api/v1/company/dashboard",
      JOBS: "/api/v1/company/jobs",
      JOB_CREATE: "/api/v1/company/jobs",
      JOB_DETAIL: (id: string | number) => `/api/v1/company/jobs/${id}`,
      JOB_UPDATE: (id: string | number) => `/api/v1/company/jobs/${id}`,
      JOB_DELETE: (id: string | number) => `/api/v1/company/jobs/${id}`,
      APPLICATIONS: "/api/v1/company/applications",
      APPLICATION_DETAIL: (id: string | number) => `/api/v1/company/applications/${id}`,
      APPLICATION_STATUS: (id: string | number) => `/api/v1/company/applications/${id}/status`,
      TALENT: "/api/v1/company/talent",
      TALENT_DETAIL: (id: string | number) => `/api/v1/company/talent/${id}`,
      TEAMS: "/api/v1/company/teams",
      TEAM_DETAIL: (id: string | number) => `/api/v1/company/teams/${id}`,
    },
    UNIVERSITY: {
      ME: "/api/v1/university/me",
      PROFILE: "/api/v1/university/profile",
      LOGO_UPLOAD: "/api/v1/university/logo",
      DASHBOARD: "/api/v1/university/dashboard",
      STUDENTS: "/api/v1/university/students",
      STUDENT_DETAIL: (id: string | number) => `/api/v1/university/students/${id}`,
      STUDENT_VERIFY_DIRECT: (id: string | number) => `/api/v1/university/students/${id}/verify`,
      VERIFICATIONS: "/api/v1/university/verifications",
      VERIFICATION_UPDATE: (id: string | number) => `/api/v1/university/verifications/${id}`,
      DEPARTMENTS: "/api/v1/university/departments",
      DEPARTMENT_DETAIL: (id: string | number) => `/api/v1/university/departments/${id}`,
      OPPORTUNITIES: "/api/v1/university/opportunities",
      EMPLOYMENT_KPIS: "/api/v1/university/employment-kpis",
      CAMPAIGNS: "/api/v1/university/campaigns",
      CAMPAIGN_DETAIL: (id: string | number) => `/api/v1/university/campaigns/${id}`,
      CAMPAIGN_INQUIRY: (id: string | number) => `/api/v1/university/campaigns/${id}/inquiry`,
      INCUBATOR: "/api/v1/university/incubator",
      COOP_SUPERVISION: "/api/v1/university/coop-supervision",
      COOP_EVALUATION: (id: string | number) => `/api/v1/university/coop-supervision/${id}/evaluation`,
      COOP_SCHEDULE: "/api/v1/university/coop-schedule",
    },
    CHAT: {
      CONVERSATIONS: "/api/v1/chat/conversations",
      CONVERSATION_DETAIL: (id: string | number) => `/api/v1/chat/conversations/${id}`,
      CREATE_CONVERSATION: "/api/v1/chat/conversations",
      SEND_MESSAGE: (id: string | number) => `/api/v1/chat/conversations/${id}/messages`,
      EDIT_MESSAGE: (id: string | number) => `/api/v1/chat/messages/${id}`,
      DELETE_MESSAGE: (id: string | number) => `/api/v1/chat/messages/${id}`,
      MARK_READ: (id: string | number) => `/api/v1/chat/conversations/${id}/read`,
      UNREAD_COUNT: "/api/v1/chat/unread-count",
    },
    ADMIN: {
      DASHBOARD: "/api/v1/admin/dashboard",
      USERS: "/api/v1/admin/users",
      USER_STATUS: (type: string, id: string | number) => `/api/v1/admin/users/${type}/${id}/status`,
      USER_VERIFY: (type: string, id: string | number) => `/api/v1/admin/users/${type}/${id}/verify`,
      USER_DELETE: (type: string, id: string | number) => `/api/v1/admin/users/${type}/${id}`,
      JOBS: "/api/v1/admin/jobs",
      JOB_STATUS: (id: string | number) => `/api/v1/admin/jobs/${id}/status`,
      JOB_DELETE: (id: string | number) => `/api/v1/admin/jobs/${id}`,
      AUDIT_LOGS: "/api/v1/admin/audit-logs",
      REPORTS: "/api/v1/admin/reports",
      REPORT_STATUS: (id: string | number) => `/api/v1/admin/reports/${id}/status`,
      SETTINGS: "/api/v1/admin/settings",
      TICKETS: "/api/v1/admin/tickets",
      TICKET_UPDATE: (id: string | number) => `/api/v1/admin/tickets/${id}`,
      CATEGORIES: "/api/v1/admin/categories",
      CATEGORY_DELETE: (type: string, id: string | number) => `/api/v1/admin/categories/${type}/${id}`,
      CATEGORY_TOGGLE: (type: string, id: string | number) => `/api/v1/admin/categories/${type}/${id}/toggle`,
    },
    CONTACT: "/api/v1/contact",
  },
}
